### ISSUE TITLE
incorrect elapsed time

### ISSUE THREAD

**Issue by phrackerjack** [3D-I/online-since#7]
**Describe the bug**
Elapsed time between current date and board start date is 4 months or so too much:

![Online Since 2020-06-10 09-41-46](https://user-images.githubusercontent.com/58938570/84279859-881c5b00-ab04-11ea-925c-77b0750ac254.png)

**Server**
Database: MySQL(i) 10.4.13-MariaDB
PHP version: 7.2.29
Board version: 3.3.0

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 (x64)
 - Browser: Firefox
 - Version: 77.0.1 (x64)

**Comment by 3D-I** [comment]
> **Describe the bug**
> Elapsed time between current date and board start date is 4 months or so too much:

Really?

![immagine](https://user-images.githubusercontent.com/480857/84280369-7d2eee00-ab37-11ea-9569-156b8aec5e4a.png)

**10-jun-2018** to **10-jun-2020** makes 2 years, 0 months, 0 days. :smile:

**Comment by phrackerjack** [comment]
> > **Describe the bug**
> > Elapsed time between current date and board start date is 4 months or so too much:
> 
> Really?
> 
> ![immagine](https://user-images.githubusercontent.com/480857/84280369-7d2eee00-ab37-11ea-9569-156b8aec5e4a.png)
> 
> **10-jun-2018** to **10-jun-2020** makes 2 years, 0 months, 0 days. smile

I thought it was reading June 10, 2018. I guess a feature request to clearly indicate the date format is in order.

**Comment by 3D-I** [comment]
So please open a feature request, thanks.
